databases:
  - name: show_geospatial_data_7b2z
    databaseName: show_geospatial_data_7b2z
    user: show_geospatial_data_7b2z_user

services:
  - type: web
    name: show_geospatial_data_7b2z
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: show_geospatial_data_7b2z
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
